# Generated by Django 4.1 on 2022-09-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo_excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arqivo', models.FileField(upload_to='Arquivo/%d/%m/%Y/')),
            ],
        ),
    ]
