# Generated by Django 4.1 on 2022-10-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo_excel', '0002_rename_arqivo_arquivo_excel_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo_excel',
            name='arquivo',
            field=models.FileField(upload_to='static/Arquivo/%d/%m/%Y/'),
        ),
    ]
