# Generated by Django 4.0.6 on 2022-07-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('descricao', models.TextField()),
                ('publico', models.CharField(choices=[('Aberto', 'Aberto'), ('Privado', 'Privado')], max_length=20)),
                ('convidados_qtd', models.IntegerField()),
            ],
        ),
    ]
