# Generated by Django 4.0.6 on 2022-07-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('nome_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastrar_eventos.evento')),
            ],
        ),
    ]
