# Generated by Django 4.0.5 on 2022-07-20 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0002_cadastro_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='habilitar_inscrever',
            field=models.BooleanField(default=False),
        ),
    ]
