# Generated by Django 4.1 on 2022-08-30 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='nome_empresa',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
