# Generated by Django 4.1 on 2022-10-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperarSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_r', models.EmailField(max_length=254)),
                ('codigo', models.IntegerField(unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('e_mail', models.EmailField(max_length=254)),
                ('grupo', models.CharField(max_length=100)),
            ],
        ),
    ]
