# Generated by Django 4.1 on 2022-10-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enviar', '0002_usuario_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperarSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_r', models.EmailField(max_length=254)),
                ('codigo', models.IntegerField(unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_vencimento', models.DateTimeField()),
            ],
        ),
    ]
