# Generated by Django 4.1 on 2022-10-24 23:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=50)),
                ('nome_evento', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 24, 20, 54, 14, 804134))),
                ('data_termino', models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 24, 20, 54, 14, 804134))),
                ('img', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('descricao', models.TextField()),
                ('publico', models.CharField(choices=[('Aberto', 'Aberto'), ('Privado', 'Privado')], max_length=20)),
                ('convidados_qtd', models.IntegerField()),
                ('publicar', models.CharField(choices=[('Não Publicado', 'Não Publicado'), ('Publicado', 'Publicado')], max_length=15)),
                ('habilitar_inscrever', models.BooleanField(default=False)),
                ('habilitar_importante', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastrar_eventos.evento')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
