# Generated by Django 4.1 on 2022-11-29 12:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=20)),
                ('nome_empresa', models.CharField(max_length=50)),
                ('nome_evento', models.CharField(max_length=50)),
                ('data_inicio', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 9, 22, 56, 847631))),
                ('data_termino', models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 9, 22, 56, 847631))),
                ('img', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('descricao', models.TextField()),
                ('publico', models.CharField(choices=[('Aberto', 'Aberto'), ('Privado', 'Privado')], max_length=20)),
                ('convidados_qtd', models.IntegerField()),
                ('publicar', models.CharField(choices=[('Não Publicado', 'Não Publicado'), ('Publicado', 'Publicado')], max_length=15)),
                ('nota_media', models.IntegerField(blank=True, default=0)),
                ('soma_notas', models.IntegerField(blank=True, default=0)),
                ('relatorios_feitos', models.IntegerField(blank=True, default=0)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio_Satisfacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(blank=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastrar_eventos.evento')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito_Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastrar_eventos.evento')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
