# Generated by Django 4.1 on 2022-11-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0002_alter_evento_data_inicio_alter_evento_data_termino'),
        ('cadastrar_eventos', '0002_inscrito_evento_email_inscrito_evento_nome_and_more'),
    ]

    operations = [
    ]
