# Generated by Django 4.0.5 on 2022-08-25 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0002_evento_data_inicio_evento_data_termino_evento_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='email',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='telefone',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 25, 20, 54, 15, 13654)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 25, 20, 54, 15, 13654)),
        ),
    ]
