# Generated by Django 4.1 on 2022-11-23 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0003_merge_20221123_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito_evento',
            name='inscritos_evento',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 23, 19, 59, 40, 792168)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 23, 19, 59, 40, 792168)),
        ),
    ]
