# Generated by Django 4.1 on 2022-11-29 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0003_alter_evento_data_inicio_alter_evento_data_termino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='soma_notas',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 9, 24, 8, 395520)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 9, 24, 8, 395520)),
        ),
    ]
