# Generated by Django 4.1 on 2022-11-23 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0004_inscrito_evento_inscritos_evento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrito_evento',
            name='inscritos_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='inscritos_evento',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 23, 20, 9, 41, 323371)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 23, 20, 9, 41, 323371)),
        ),
    ]
