# Generated by Django 4.1 on 2022-11-29 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0004_remove_evento_soma_notas_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='soma_notas',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 9, 24, 27, 667361)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 29, 9, 24, 27, 667361)),
        ),
    ]
