# Generated by Django 4.1 on 2022-11-24 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0007_remove_evento_inscritos_evento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscritos_evento',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 24, 14, 44, 23, 795246)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 24, 14, 44, 23, 795246)),
        ),
    ]
