# Generated by Django 4.1 on 2022-11-24 21:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0008_evento_inscritos_evento_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='inscritos_evento',
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 24, 18, 47, 43, 90758)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 24, 18, 47, 43, 90758)),
        ),
    ]
