# Generated by Django 4.1 on 2022-09-05 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0012_alter_evento_data_inicio_alter_evento_data_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='publicar',
            field=models.CharField(choices=[('Não Publicado', 'Não Publicado'), ('Publicado', 'Publicado')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 5, 18, 25, 32, 62156)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 5, 18, 25, 32, 62156)),
        ),
    ]
