# Generated by Django 4.1 on 2022-10-21 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0013_evento_publicar_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 8, 27, 3, 759466)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 10, 21, 8, 27, 3, 759466)),
        ),
    ]
