# Generated by Django 4.0.5 on 2022-08-20 00:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 19, 21, 1, 46, 886919)),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_termino',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 8, 19, 21, 1, 46, 886919)),
        ),
        migrations.AddField(
            model_name='evento',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_completo',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='nome_empresa',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='telefone',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Cadastro_Evento',
        ),
    ]
