# Generated by Django 4.1 on 2022-09-06 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastrar_eventos', '0013_evento_publicar_alter_evento_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 6, 19, 46, 56, 165423)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_termino',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 6, 19, 46, 56, 167430)),
        ),
    ]
