# Generated by Django 4.1 on 2022-09-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arquivo_excel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arquivo_excel',
            old_name='arqivo',
            new_name='arquivo',
        ),
    ]
